services:
  nginx:
    image: nginx:latest
    container_name: ${PROJECT_PREFIX}nginx-container
    ports:
      - "${APP_PORT}:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/logs/nginx/:/var/log/nginx/
      - ./backend/public/:/var/www/backend_public
    tty: true
    networks:
      - ipr

  php:
    build:
      context: ./docker/php
      args:
        HOST_GID: ${HOST_GID}
        HOST_UID: ${HOST_UID}
        ENV: ${API_ENV}
        TZ: ${TZ}
    container_name: ${PROJECT_PREFIX}backend-container
    environment:
      - TZ
      # only for dev
      - PHP_IDE_CONFIG
      - XDEBUG_SESSION
      - APP_ENV=${API_ENV}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./backend/:/var/www/app/:cached
      - ./docker/logs/symfony:/var/www/var/log:cached
    networks:
      - ipr
    tty: true

networks:
  ipr:
    name: ipr
