services:
  nginx:
    image: nginx:latest
    container_name: ${PROJECT_PREFIX}nginx-container
    ports:
      - "${APP_PORT}:80"
    volumes:
      - ./docker/nginx/:/etc/nginx/conf.d/
      - ./docker/logs/nginx/:/var/log/nginx/
      - ./backend/public/:/var/www/backend/public/:cached
    tty: true
    networks:
      - ipr

  php:
    build:
      context: ./docker/php
      args:
        HOST_GID: ${HOST_GID}
        HOST_UID: ${HOST_UID}
        APP_ENV: ${API_ENV}
        TZ: ${TZ}
    container_name: ${PROJECT_PREFIX}backend-container
    user: "${HOST_UID}:${HOST_GID}"
    environment:
      - TZ
      # only for dev
      - PHP_IDE_CONFIG
      - XDEBUG_SESSION
      - APP_ENV=${API_ENV}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./backend/:/var/www/backend/:cached
    networks:
      - ipr
    tty: true

networks:
  ipr:
    name: ipr
