services:
  nginx:
    image: nginx:latest
    container_name: ${PROJECT_PREFIX}nginx-container
    ports:
      - "${APP_PORT}:80"
    volumes:
      - ./docker/nginx/:/etc/nginx/conf.d/
      - ./docker/logs/nginx/:/var/log/nginx/
      - ./backend/public/:/var/www/backend/public/:cached
    tty: true
    networks:
      - ipr

  php:
    build:
      context: ./docker/php
      args:
        HOST_GID: ${HOST_GID}
        HOST_UID: ${HOST_UID}
        APP_ENV: ${API_ENV}
        TZ: ${TZ}
    container_name: ${PROJECT_PREFIX}backend-container
    user: "${HOST_UID}:${HOST_GID}"
    environment:
      - TZ
      # only for dev
      - PHP_IDE_CONFIG
      - XDEBUG_SESSION
      - APP_ENV=${API_ENV}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./backend/:/var/www/backend/:cached
    networks:
      - ipr
    tty: true

  database:
    image: postgres:${POSTGRES_VERSION:-16}-alpine
    container_name: ${PROJECT_PREFIX}database
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    volumes:
      #- database_data:/var/lib/postgresql/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      - ./docker/db/data:/var/lib/postgresql/data:rw
    ports:
      - "32768:5432"
    networks:
      - ipr

networks:
  ipr:
    name: ipr
