security:
    access_decision_manager:
        strategy: unanimous
    providers:
        app_user_provider:
            id: App\Authentication\User\SecurityUserProvider

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|api/_docs)
            security: false
        public:
            pattern: ^/(login|login_check|register|$)
            security: false
        public_api:
            pattern: ^/(api/users/login|api/users/register)
            stateless: true
            security: false
        api:
            pattern: ^/api
            stateless: false
            lazy: true
            context: session #for the seek of frontend and mobile app
            custom_authenticators:
                - App\Authentication\ApiTokenAuthenticator
                - App\Authentication\SiteAuthenticator #for the seek of frontend and mobile app
        site:
            pattern: ^/
            lazy: true
            context: session
            #user_checker: App\Security\UserChecker add to project
            logout:
                path: /logout
                target: /
            custom_authenticators:
                - App\Authentication\SiteAuthenticator
    access_control:
        - { path: ^/, roles: IS_AUTHENTICATED_FULLY }

